modules:
  default:
    metrics:
    - name: example
      path: "{ [*] }"
      help: Example metric
      labels:
        environment: static
        location: "planet-{.location}"
      restrictions:
        - not_empty_response
        - not_null:
          - "{.name}"
  not_default:
    metrics:
      - name: not_default example
      